INFO 2025-05-30 12:17:21,068 autoreload 2160 21584 Watching for file changes with StatReloader
INFO 2025-05-30 12:21:41,581 autoreload 2160 21584 D:\PMC\sims_project\sims_project\settings.py changed, reloading.
INFO 2025-05-30 12:21:42,507 autoreload 20044 9412 Watching for file changes with StatReloader
INFO 2025-05-30 12:21:42,659 wsgi 20044 22252 SIMS WSGI application initialized successfully
INFO 2025-05-30 12:21:49,497 basehttp 20044 11088 "GET /admin HTTP/1.1" 301 0
INFO 2025-05-30 12:21:49,634 basehttp 20044 13752 "GET /admin/ HTTP/1.1" 302 0
ERROR 2025-05-30 12:21:49,879 log 20044 13752 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 169, in render
    with context.bind_template(self):
         ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\context.py", line 256, in bind_template
    processors = template.engine.template_context_processors + self._processors
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 118, in template_context_processors
    return tuple(import_string(path) for path in context_processors)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 118, in <genexpr>
    return tuple(import_string(path) for path in context_processors)
                 ~~~~~~~~~~~~~^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sims.users.context_processors'
ERROR 2025-05-30 12:21:49,888 basehttp 20044 13752 "GET /admin/login/?next=/admin/ HTTP/1.1" 500 132566
WARNING 2025-05-30 12:21:50,066 log 20044 13752 Not Found: /favicon.ico
WARNING 2025-05-30 12:21:50,067 basehttp 20044 13752 "GET /favicon.ico HTTP/1.1" 404 3810
INFO 2025-05-30 12:21:52,120 autoreload 20044 9412 D:\PMC\sims_project\sims_project\settings.py changed, reloading.
INFO 2025-05-30 12:21:52,783 autoreload 10112 5496 Watching for file changes with StatReloader
INFO 2025-05-30 12:21:52,870 wsgi 10112 11740 SIMS WSGI application initialized successfully
INFO 2025-05-30 12:23:07,279 basehttp 10112 16244 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4164
INFO 2025-05-30 12:23:07,364 basehttp 10112 16244 "GET /static/admin/css/base.css HTTP/1.1" 200 22120
INFO 2025-05-30 12:23:07,366 basehttp 10112 15552 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2808
INFO 2025-05-30 12:23:07,377 basehttp 10112 15552 "GET /static/admin/css/login.css HTTP/1.1" 200 951
INFO 2025-05-30 12:23:07,377 basehttp 10112 16244 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-05-30 12:23:07,389 basehttp 10112 15552 "GET /static/admin/css/responsive.css HTTP/1.1" 200 16565
INFO 2025-05-30 12:23:07,409 basehttp 10112 16244 "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-05-30 12:23:07,410 basehttp 10112 15552 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-05-30 12:31:22,134 autoreload 10112 5496 D:\PMC\sims_project\sims\users\views.py changed, reloading.
INFO 2025-05-30 12:31:22,958 autoreload 11468 20592 Watching for file changes with StatReloader
INFO 2025-05-30 12:31:23,043 wsgi 11468 13984 SIMS WSGI application initialized successfully
INFO 2025-05-30 12:31:37,603 basehttp 11468 22616 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4332
INFO 2025-05-30 12:31:47,076 basehttp 11468 22616 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4331
INFO 2025-05-30 12:33:15,937 basehttp 11468 22220 "GET /admin?id=25b08912-a267-4967-a32b-26f5876aa7f5&vscodeBrowserReqId=1748590395894 HTTP/1.1" 301 0
INFO 2025-05-30 12:33:15,952 basehttp 11468 19760 "GET /admin/?id=25b08912-a267-4967-a32b-26f5876aa7f5&vscodeBrowserReqId=1748590395894 HTTP/1.1" 302 0
INFO 2025-05-30 12:33:15,967 basehttp 11468 19760 "GET /admin/login/?next=/admin/%3Fid%3D25b08912-a267-4967-a32b-26f5876aa7f5%26vscodeBrowserReqId%3D1748590395894 HTTP/1.1" 200 4322
INFO 2025-05-30 12:33:24,129 basehttp 11468 14472 "GET /?id=25b08912-a267-4967-a32b-26f5876aa7f5&vscodeBrowserReqId=1748590404122 HTTP/1.1" 200 59
INFO 2025-05-30 12:33:38,188 basehttp 11468 23032 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4331
INFO 2025-05-30 12:34:35,010 autoreload 8752 23284 Watching for file changes with StatReloader
INFO 2025-05-30 12:34:48,362 basehttp 11468 14460 "GET /?id=25b08912-a267-4967-a32b-26f5876aa7f5&vscodeBrowserReqId=1748590488349 HTTP/1.1" 200 59
INFO 2025-05-30 12:34:52,813 basehttp 11468 15724 "GET /admin?id=25b08912-a267-4967-a32b-26f5876aa7f5&vscodeBrowserReqId=1748590492792 HTTP/1.1" 301 0
INFO 2025-05-30 12:34:52,821 basehttp 11468 18396 "GET /admin/?id=25b08912-a267-4967-a32b-26f5876aa7f5&vscodeBrowserReqId=1748590492792 HTTP/1.1" 302 0
INFO 2025-05-30 12:34:52,836 basehttp 11468 18396 "GET /admin/login/?next=/admin/%3Fid%3D25b08912-a267-4967-a32b-26f5876aa7f5%26vscodeBrowserReqId%3D1748590492792 HTTP/1.1" 200 4322
INFO 2025-05-30 12:34:54,543 basehttp 11468 22696 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-05-30 12:34:54,651 basehttp 11468 22696 "GET /admin/ HTTP/1.1" 200 20033
INFO 2025-05-30 12:34:54,839 basehttp 11468 22696 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2025-05-30 12:34:54,843 basehttp 11468 16016 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-05-30 12:34:54,857 basehttp 11468 22696 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
WARNING 2025-05-30 12:35:05,001 log 11468 16004 Not Found: /users/
WARNING 2025-05-30 12:35:05,002 basehttp 11468 16004 "GET /users/?id=25b08912-a267-4967-a32b-26f5876aa7f5&vscodeBrowserReqId=1748590504988 HTTP/1.1" 404 12063
INFO 2025-05-30 12:36:17,915 basehttp 11468 6040 "GET /health?id=25b08912-a267-4967-a32b-26f5876aa7f5&vscodeBrowserReqId=1748590577891 HTTP/1.1" 301 0
INFO 2025-05-30 12:36:17,922 basehttp 11468 6136 "GET /health/?id=25b08912-a267-4967-a32b-26f5876aa7f5&vscodeBrowserReqId=1748590577891 HTTP/1.1" 200 2
INFO 2025-05-30 12:37:17,905 basehttp 11468 21576 "GET /cases/?id=25b08912-a267-4967-a32b-26f5876aa7f5&vscodeBrowserReqId=1748590637891 HTTP/1.1" 302 0
ERROR 2025-05-30 12:37:17,999 log 11468 21576 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/login.html
ERROR 2025-05-30 12:37:18,006 basehttp 11468 21576 "GET /users/login/?next=/cases/%3Fid%3D25b08912-a267-4967-a32b-26f5876aa7f5%26vscodeBrowserReqId%3D1748590637891 HTTP/1.1" 500 88362
INFO 2025-05-30 12:37:25,435 basehttp 11468 8392 "GET /logbook/?id=25b08912-a267-4967-a32b-26f5876aa7f5&vscodeBrowserReqId=1748590645425 HTTP/1.1" 302 0
ERROR 2025-05-30 12:37:25,450 log 11468 8392 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/login.html
ERROR 2025-05-30 12:37:25,451 basehttp 11468 8392 "GET /users/login/?next=/logbook/%3Fid%3D25b08912-a267-4967-a32b-26f5876aa7f5%26vscodeBrowserReqId%3D1748590645425 HTTP/1.1" 500 88374
INFO 2025-05-30 12:37:37,758 basehttp 11468 22044 "GET /rotations/?id=25b08912-a267-4967-a32b-26f5876aa7f5&vscodeBrowserReqId=1748590657750 HTTP/1.1" 302 0
ERROR 2025-05-30 12:37:37,813 log 11468 22044 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/login.html
ERROR 2025-05-30 12:37:37,816 basehttp 11468 22044 "GET /users/login/?next=/rotations/%3Fid%3D25b08912-a267-4967-a32b-26f5876aa7f5%26vscodeBrowserReqId%3D1748590657750 HTTP/1.1" 500 88386
INFO 2025-05-30 12:37:56,158 basehttp 11468 22044 "GET /certificates/?id=25b08912-a267-4967-a32b-26f5876aa7f5&vscodeBrowserReqId=1748590676151 HTTP/1.1" 302 0
ERROR 2025-05-30 12:37:56,172 log 11468 22044 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/login.html
ERROR 2025-05-30 12:37:56,173 basehttp 11468 22044 "GET /users/login/?next=/certificates/%3Fid%3D25b08912-a267-4967-a32b-26f5876aa7f5%26vscodeBrowserReqId%3D1748590676151 HTTP/1.1" 500 88404
INFO 2025-05-30 12:38:44,537 autoreload 11468 20592 D:\PMC\sims_project\sims_project\settings.py changed, reloading.
INFO 2025-05-30 12:38:44,668 autoreload 8752 23284 D:\PMC\sims_project\sims\users\forms.py changed, reloading.
INFO 2025-05-30 12:38:45,479 autoreload 16908 11764 Watching for file changes with StatReloader
INFO 2025-05-30 12:38:45,479 autoreload 16864 22920 Watching for file changes with StatReloader
INFO 2025-05-30 12:38:45,563 wsgi 16908 10300 SIMS WSGI application initialized successfully
